Logging from pod postgres-64d5fd7b85-l5dhr in namespace default

PostgreSQL Database directory appears to contain a database; Skipping initialization

2024-12-16 09:27:24.240 UTC [1] LOG:  starting PostgreSQL 16.4 (Debian 16.4-1.pgdg120+2) on x86_64-pc-linux-gnu, compiled by gcc (Debian 12.2.0-14) 12.2.0, 64-bit
2024-12-16 09:27:24.241 UTC [1] LOG:  listening on IPv4 address "0.0.0.0", port 5432
2024-12-16 09:27:24.241 UTC [1] LOG:  listening on IPv6 address "::", port 5432
2024-12-16 09:27:24.281 UTC [1] LOG:  listening on Unix socket "/var/run/postgresql/.s.PGSQL.5432"
2024-12-16 09:27:24.333 UTC [29] LOG:  database system was interrupted; last known up at 2024-12-16 08:02:01 UTC
2024-12-16 09:27:27.250 UTC [29] LOG:  database system was not properly shut down; automatic recovery in progress
2024-12-16 09:27:27.266 UTC [29] LOG:  redo starts at 0/2384FA0
2024-12-16 09:27:27.267 UTC [29] LOG:  invalid record length at 0/2384FD8: expected at least 24, got 0
2024-12-16 09:27:27.267 UTC [29] LOG:  redo done at 0/2384FA0 system usage: CPU: user: 0.00 s, system: 0.00 s, elapsed: 0.00 s
2024-12-16 09:27:27.285 UTC [27] LOG:  checkpoint starting: end-of-recovery immediate wait
2024-12-16 09:27:27.353 UTC [27] LOG:  checkpoint complete: wrote 3 buffers (0.0%); 0 WAL file(s) added, 0 removed, 0 recycled; write=0.011 s, sync=0.006 s, total=0.080 s; sync files=2, longest=0.004 s, average=0.003 s; distance=0 kB, estimate=0 kB; lsn=0/2384FD8, redo lsn=0/2384FD8
2024-12-16 09:27:27.376 UTC [1] LOG:  database system is ready to accept connections
Logging from container postgres in pod postgres-64d5fd7b85-l5dhr in namespace default

PostgreSQL Database directory appears to contain a database; Skipping initialization

2024-12-16 09:27:24.240 UTC [1] LOG:  starting PostgreSQL 16.4 (Debian 16.4-1.pgdg120+2) on x86_64-pc-linux-gnu, compiled by gcc (Debian 12.2.0-14) 12.2.0, 64-bit
2024-12-16 09:27:24.241 UTC [1] LOG:  listening on IPv4 address "0.0.0.0", port 5432
2024-12-16 09:27:24.241 UTC [1] LOG:  listening on IPv6 address "::", port 5432
2024-12-16 09:27:24.281 UTC [1] LOG:  listening on Unix socket "/var/run/postgresql/.s.PGSQL.5432"
2024-12-16 09:27:24.333 UTC [29] LOG:  database system was interrupted; last known up at 2024-12-16 08:02:01 UTC
2024-12-16 09:27:27.250 UTC [29] LOG:  database system was not properly shut down; automatic recovery in progress
2024-12-16 09:27:27.266 UTC [29] LOG:  redo starts at 0/2384FA0
2024-12-16 09:27:27.267 UTC [29] LOG:  invalid record length at 0/2384FD8: expected at least 24, got 0
2024-12-16 09:27:27.267 UTC [29] LOG:  redo done at 0/2384FA0 system usage: CPU: user: 0.00 s, system: 0.00 s, elapsed: 0.00 s
2024-12-16 09:27:27.285 UTC [27] LOG:  checkpoint starting: end-of-recovery immediate wait
2024-12-16 09:27:27.353 UTC [27] LOG:  checkpoint complete: wrote 3 buffers (0.0%); 0 WAL file(s) added, 0 removed, 0 recycled; write=0.011 s, sync=0.006 s, total=0.080 s; sync files=2, longest=0.004 s, average=0.003 s; distance=0 kB, estimate=0 kB; lsn=0/2384FD8, redo lsn=0/2384FD8
2024-12-16 09:27:27.376 UTC [1] LOG:  database system is ready to accept connections
Logging from pod backend-deployment-787d99bf76-2tz2q in namespace default
INFO:root:Database session created successfully.
INFO:root:Labels already exist.
 * Serving Flask app 'run.py'
 * Debug mode: off
INFO:werkzeug:[31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:5000
 * Running on http://10.42.0.200:5000
INFO:werkzeug:[33mPress CTRL+C to quit[0m
Logging from container backend in pod backend-deployment-787d99bf76-2tz2q in namespace default
INFO:root:Database session created successfully.
INFO:root:Labels already exist.
 * Serving Flask app 'run.py'
 * Debug mode: off
INFO:werkzeug:[31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:5000
 * Running on http://10.42.0.200:5000
INFO:werkzeug:[33mPress CTRL+C to quit[0m
Logging from pod backend-deployment-787d99bf76-5h6sx in namespace default
INFO:root:Database session created successfully.
INFO:root:Labels already exist.
 * Serving Flask app 'run.py'
 * Debug mode: off
INFO:werkzeug:[31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:5000
 * Running on http://10.42.0.199:5000
INFO:werkzeug:[33mPress CTRL+C to quit[0m
INFO:root:Database session created successfully.
ERROR:root:Error in fetch_transactions_overview: 'list' object has no attribute 'values'
INFO:werkzeug:10.42.0.202 - - [16/Dec/2024 09:47:51] "[35m[1mGET /api/fetch-transactions-overview HTTP/1.0[0m" 500 -
INFO:root:Database session created successfully.
ERROR:root:Error in fetch_transactions_overview: 'list' object has no attribute 'values'
INFO:werkzeug:10.42.0.202 - - [16/Dec/2024 09:47:52] "[35m[1mGET /api/fetch-transactions-overview HTTP/1.0[0m" 500 -
INFO:root:Database session created successfully.
ERROR:root:Error in fetch_transactions_overview: 'list' object has no attribute 'values'
INFO:werkzeug:10.42.0.202 - - [16/Dec/2024 09:47:52] "[35m[1mGET /api/fetch-transactions-overview HTTP/1.0[0m" 500 -
INFO:root:Database session created successfully.
ERROR:root:Error in fetch_transactions_overview: 'list' object has no attribute 'values'
INFO:werkzeug:10.42.0.205 - - [16/Dec/2024 09:50:51] "[35m[1mGET /api/fetch-transactions-overview HTTP/1.0[0m" 500 -
Logging from container backend in pod backend-deployment-787d99bf76-5h6sx in namespace default
INFO:root:Database session created successfully.
INFO:root:Labels already exist.
 * Serving Flask app 'run.py'
 * Debug mode: off
INFO:werkzeug:[31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:5000
 * Running on http://10.42.0.199:5000
INFO:werkzeug:[33mPress CTRL+C to quit[0m
INFO:root:Database session created successfully.
ERROR:root:Error in fetch_transactions_overview: 'list' object has no attribute 'values'
INFO:werkzeug:10.42.0.202 - - [16/Dec/2024 09:47:51] "[35m[1mGET /api/fetch-transactions-overview HTTP/1.0[0m" 500 -
INFO:root:Database session created successfully.
ERROR:root:Error in fetch_transactions_overview: 'list' object has no attribute 'values'
INFO:werkzeug:10.42.0.202 - - [16/Dec/2024 09:47:52] "[35m[1mGET /api/fetch-transactions-overview HTTP/1.0[0m" 500 -
INFO:root:Database session created successfully.
ERROR:root:Error in fetch_transactions_overview: 'list' object has no attribute 'values'
INFO:werkzeug:10.42.0.202 - - [16/Dec/2024 09:47:52] "[35m[1mGET /api/fetch-transactions-overview HTTP/1.0[0m" 500 -
INFO:root:Database session created successfully.
ERROR:root:Error in fetch_transactions_overview: 'list' object has no attribute 'values'
INFO:werkzeug:10.42.0.205 - - [16/Dec/2024 09:50:51] "[35m[1mGET /api/fetch-transactions-overview HTTP/1.0[0m" 500 -
Logging from pod frontend-deployment-59cfb65b7-gg7tm in namespace default
/docker-entrypoint.sh: /docker-entrypoint.d/ is not empty, will attempt to perform configuration
/docker-entrypoint.sh: Looking for shell scripts in /docker-entrypoint.d/
/docker-entrypoint.sh: Launching /docker-entrypoint.d/10-listen-on-ipv6-by-default.sh
10-listen-on-ipv6-by-default.sh: info: Getting the checksum of /etc/nginx/conf.d/default.conf
10-listen-on-ipv6-by-default.sh: info: Enabled listen on IPv6 in /etc/nginx/conf.d/default.conf
/docker-entrypoint.sh: Sourcing /docker-entrypoint.d/15-local-resolvers.envsh
/docker-entrypoint.sh: Launching /docker-entrypoint.d/20-envsubst-on-templates.sh
/docker-entrypoint.sh: Launching /docker-entrypoint.d/30-tune-worker-processes.sh
/docker-entrypoint.sh: Configuration complete; ready for start up
10.42.0.1 - - [16/Dec/2024:09:50:51 +0000] "GET /api/fetch-transactions-overview HTTP/1.1" 500 52 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/131.0.0.0 Safari/537.36"
10.42.0.1 - - [16/Dec/2024:09:50:55 +0000] "GET /api/fetch-transactions-overview HTTP/1.1" 500 52 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/131.0.0.0 Safari/537.36"
10.42.0.1 - - [16/Dec/2024:09:50:56 +0000] "GET /api/fetch-transactions-overview HTTP/1.1" 500 52 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/131.0.0.0 Safari/537.36"
Logging from container frontend in pod frontend-deployment-59cfb65b7-gg7tm in namespace default
/docker-entrypoint.sh: /docker-entrypoint.d/ is not empty, will attempt to perform configuration
/docker-entrypoint.sh: Looking for shell scripts in /docker-entrypoint.d/
/docker-entrypoint.sh: Launching /docker-entrypoint.d/10-listen-on-ipv6-by-default.sh
10-listen-on-ipv6-by-default.sh: info: Getting the checksum of /etc/nginx/conf.d/default.conf
10-listen-on-ipv6-by-default.sh: info: Enabled listen on IPv6 in /etc/nginx/conf.d/default.conf
/docker-entrypoint.sh: Sourcing /docker-entrypoint.d/15-local-resolvers.envsh
/docker-entrypoint.sh: Launching /docker-entrypoint.d/20-envsubst-on-templates.sh
/docker-entrypoint.sh: Launching /docker-entrypoint.d/30-tune-worker-processes.sh
/docker-entrypoint.sh: Configuration complete; ready for start up
10.42.0.1 - - [16/Dec/2024:09:50:51 +0000] "GET /api/fetch-transactions-overview HTTP/1.1" 500 52 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/131.0.0.0 Safari/537.36"
10.42.0.1 - - [16/Dec/2024:09:50:55 +0000] "GET /api/fetch-transactions-overview HTTP/1.1" 500 52 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/131.0.0.0 Safari/537.36"
10.42.0.1 - - [16/Dec/2024:09:50:56 +0000] "GET /api/fetch-transactions-overview HTTP/1.1" 500 52 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/131.0.0.0 Safari/537.36"
Logging from pod frontend-deployment-59cfb65b7-j8clb in namespace default
/docker-entrypoint.sh: /docker-entrypoint.d/ is not empty, will attempt to perform configuration
/docker-entrypoint.sh: Looking for shell scripts in /docker-entrypoint.d/
/docker-entrypoint.sh: Launching /docker-entrypoint.d/10-listen-on-ipv6-by-default.sh
10-listen-on-ipv6-by-default.sh: info: Getting the checksum of /etc/nginx/conf.d/default.conf
10-listen-on-ipv6-by-default.sh: info: Enabled listen on IPv6 in /etc/nginx/conf.d/default.conf
/docker-entrypoint.sh: Sourcing /docker-entrypoint.d/15-local-resolvers.envsh
/docker-entrypoint.sh: Launching /docker-entrypoint.d/20-envsubst-on-templates.sh
/docker-entrypoint.sh: Launching /docker-entrypoint.d/30-tune-worker-processes.sh
/docker-entrypoint.sh: Configuration complete; ready for start up
Logging from container frontend in pod frontend-deployment-59cfb65b7-j8clb in namespace default
/docker-entrypoint.sh: /docker-entrypoint.d/ is not empty, will attempt to perform configuration
/docker-entrypoint.sh: Looking for shell scripts in /docker-entrypoint.d/
/docker-entrypoint.sh: Launching /docker-entrypoint.d/10-listen-on-ipv6-by-default.sh
10-listen-on-ipv6-by-default.sh: info: Getting the checksum of /etc/nginx/conf.d/default.conf
10-listen-on-ipv6-by-default.sh: info: Enabled listen on IPv6 in /etc/nginx/conf.d/default.conf
/docker-entrypoint.sh: Sourcing /docker-entrypoint.d/15-local-resolvers.envsh
/docker-entrypoint.sh: Launching /docker-entrypoint.d/20-envsubst-on-templates.sh
/docker-entrypoint.sh: Launching /docker-entrypoint.d/30-tune-worker-processes.sh
/docker-entrypoint.sh: Configuration complete; ready for start up
Logging from pod backend-deployment-787d99bf76-b98vf in namespace default
INFO:root:Database session created successfully.
INFO:root:Labels already exist.
 * Serving Flask app 'run.py'
 * Debug mode: off
INFO:werkzeug:[31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:5000
 * Running on http://10.42.0.203:5000
INFO:werkzeug:[33mPress CTRL+C to quit[0m
INFO:root:Database session created successfully.
ERROR:root:Error in fetch_transactions_overview: 'list' object has no attribute 'values'
Traceback (most recent call last):
  File "/app/app/db.py", line 803, in fetch_transactions_overview
    add_category_to_overview(category)
  File "/app/app/db.py", line 777, in add_category_to_overview
    parent_overview = find_category_in_overview(overview, parent_name)
  File "/app/app/db.py", line 791, in find_category_in_overview
    result = find_category_in_overview(subcategory['subcategories'], category_name)
  File "/app/app/db.py", line 789, in find_category_in_overview
    for subcategory in overview.values():
AttributeError: 'list' object has no attribute 'values'
INFO:werkzeug:10.42.0.205 - - [16/Dec/2024 09:50:55] "[35m[1mGET /api/fetch-transactions-overview HTTP/1.0[0m" 500 -
Logging from container backend in pod backend-deployment-787d99bf76-b98vf in namespace default
INFO:root:Database session created successfully.
INFO:root:Labels already exist.
 * Serving Flask app 'run.py'
 * Debug mode: off
INFO:werkzeug:[31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:5000
 * Running on http://10.42.0.203:5000
INFO:werkzeug:[33mPress CTRL+C to quit[0m
INFO:root:Database session created successfully.
ERROR:root:Error in fetch_transactions_overview: 'list' object has no attribute 'values'
Traceback (most recent call last):
  File "/app/app/db.py", line 803, in fetch_transactions_overview
    add_category_to_overview(category)
  File "/app/app/db.py", line 777, in add_category_to_overview
    parent_overview = find_category_in_overview(overview, parent_name)
  File "/app/app/db.py", line 791, in find_category_in_overview
    result = find_category_in_overview(subcategory['subcategories'], category_name)
  File "/app/app/db.py", line 789, in find_category_in_overview
    for subcategory in overview.values():
AttributeError: 'list' object has no attribute 'values'
INFO:werkzeug:10.42.0.205 - - [16/Dec/2024 09:50:55] "[35m[1mGET /api/fetch-transactions-overview HTTP/1.0[0m" 500 -
Logging from pod backend-deployment-787d99bf76-2pswc in namespace default
INFO:root:Database session created successfully.
INFO:root:Labels already exist.
 * Serving Flask app 'run.py'
 * Debug mode: off
INFO:werkzeug:[31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:5000
 * Running on http://10.42.0.204:5000
INFO:werkzeug:[33mPress CTRL+C to quit[0m
INFO:root:Database session created successfully.
ERROR:root:Error in fetch_transactions_overview: 'list' object has no attribute 'values'
Traceback (most recent call last):
  File "/app/app/db.py", line 803, in fetch_transactions_overview
    add_category_to_overview(category)
  File "/app/app/db.py", line 777, in add_category_to_overview
    parent_overview = find_category_in_overview(overview, parent_name)
  File "/app/app/db.py", line 791, in find_category_in_overview
    result = find_category_in_overview(subcategory['subcategories'], category_name)
  File "/app/app/db.py", line 789, in find_category_in_overview
    for subcategory in overview.values():
AttributeError: 'list' object has no attribute 'values'
INFO:werkzeug:10.42.0.205 - - [16/Dec/2024 09:50:56] "[35m[1mGET /api/fetch-transactions-overview HTTP/1.0[0m" 500 -
Logging from container backend in pod backend-deployment-787d99bf76-2pswc in namespace default
INFO:root:Database session created successfully.
INFO:root:Labels already exist.
 * Serving Flask app 'run.py'
 * Debug mode: off
INFO:werkzeug:[31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:5000
 * Running on http://10.42.0.204:5000
INFO:werkzeug:[33mPress CTRL+C to quit[0m
INFO:root:Database session created successfully.
ERROR:root:Error in fetch_transactions_overview: 'list' object has no attribute 'values'
Traceback (most recent call last):
  File "/app/app/db.py", line 803, in fetch_transactions_overview
    add_category_to_overview(category)
  File "/app/app/db.py", line 777, in add_category_to_overview
    parent_overview = find_category_in_overview(overview, parent_name)
  File "/app/app/db.py", line 791, in find_category_in_overview
    result = find_category_in_overview(subcategory['subcategories'], category_name)
  File "/app/app/db.py", line 789, in find_category_in_overview
    for subcategory in overview.values():
AttributeError: 'list' object has no attribute 'values'
INFO:werkzeug:10.42.0.205 - - [16/Dec/2024 09:50:56] "[35m[1mGET /api/fetch-transactions-overview HTTP/1.0[0m" 500 -
